name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none

variables:
- group: 'demo-sub-keyvault-group'

stages :
  - stage: arm_template_deploy
    jobs:
      - job: arm_template_deploy
        steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'azure-arm-demo-connection'
              subscriptionId: $(demoSubSecret)
              action: 'Create or Update Resource Group'
              resourceGroupName: 'demoRG'
              location: 'westeurope'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.DefaultWorkingDirectory)/template/vnet-config.json'
              csmParametersFile: '$(System.DefaultWorkingDirectory)/template/vnet.parameters.json'
              deploymentMode: 'Incremental'




